### DISCUSSION TITLE
Building a Rust project against a user-local GTK4 Layer Shell

### DISCUSSION THREAD

**Discussion by wmww** [wmww/gtk4-layer-shell#18] [General]
Since the library isn't packaged for the distro I'm using and I don't like manually installing stuff to system directories, I figured out how to build and run a Rust project against a copy of the library installed to an arbitrary directory.

First, we build GTK4 Layer Shell and install it into a subdirectory 
```bash
meson setup build --prefix "$PWD/install"
ninja -C build install
```

And next in our Rust project we create `.cargo/config.toml` and put in it (set the paths to be correct):
```toml
[env]
PKG_CONFIG_PATH = "/path/to/gtk4-layer-shell/install/lib/x86_64-linux-gnu/pkgconfig"
LD_PRELOAD = "/path/to/gtk4-layer-shell/install/lib/x86_64-linux-gnu/libgtk4-layer-shell.so"
```

We need to use `LD_PRELOAD` instead of `LD_LIBRARY_PATH`  because rust clobbers the latter.
